  -- Global Community Chat — начальные данные (Бишкек).
  -- Сгенерировано из данных frontend-прототипа (src/mocks) один раз; после применения
  -- источником истины становится база. Повторный запуск ничего не дублирует (on conflict do nothing).

  -- ── Города и районы ──
  insert into public.cities (id, name) values
    ('bishkek', 'Бишкек')
  on conflict (id) do nothing;

  insert into public.districts (id, city_id, name) values
    ('pervomaisky', 'bishkek', 'Первомайский район'),
    ('leninsky', 'bishkek', 'Ленинский район'),
    ('sverdlovsky', 'bishkek', 'Свердловский район'),
    ('oktyabrsky', 'bishkek', 'Октябрьский район')
  on conflict (id) do nothing;

  -- ── Учебные заведения (123) ──
  insert into public.institutions (district_id, id, city_id, type, name, full_name) values
    ('pervomaisky', 'knu', 'bishkek', 'university', 'КНУ им. Ж. Баласагына', 'Кыргызский национальный университет'),
    ('pervomaisky', 'kgma', 'bishkek', 'university', 'КГМА им. И. К. Ахунбаева', 'Кыргызская государственная медицинская академия'),
    ('pervomaisky', 'kgu', 'bishkek', 'university', 'КГУ им. И. Арабаева', 'Кыргызский государственный университет'),
    ('pervomaisky', 'auca', 'bishkek', 'university', 'АУЦА', 'Американский университет в Центральной Азии'),
    ('pervomaisky', 'knk', 'bishkek', 'university', 'КНК им. К. Молдобасанова', 'Кыргызская национальная консерватория'),
    ('pervomaisky', 'school-1', 'bishkek', 'school', 'Школа №1', null),
    ('pervomaisky', 'school-6', 'bishkek', 'school', 'Школа №6', null),
    ('pervomaisky', 'school-15', 'bishkek', 'school', 'Школа №15', null),
    ('pervomaisky', 'school-18', 'bishkek', 'school', 'Школа №18', null),
    ('pervomaisky', 'school-19', 'bishkek', 'school', 'Школа №19', null),
    ('pervomaisky', 'school-24', 'bishkek', 'school', 'Школа №24', null),
    ('pervomaisky', 'school-27', 'bishkek', 'school', 'Школа №27', null),
    ('pervomaisky', 'school-28', 'bishkek', 'school', 'Школа №28', null),
    ('pervomaisky', 'school-29', 'bishkek', 'school', 'Школа №29', null),
    ('pervomaisky', 'school-41', 'bishkek', 'school', 'Школа №41', null),
    ('pervomaisky', 'school-48', 'bishkek', 'school', 'Школа №48', null),
    ('pervomaisky', 'school-49', 'bishkek', 'school', 'Школа №49', null),
    ('pervomaisky', 'school-54', 'bishkek', 'school', 'Школа №54', null),
    ('pervomaisky', 'school-61', 'bishkek', 'school', 'Школа №61', null),
    ('pervomaisky', 'school-69', 'bishkek', 'school', 'Школа №69', null),
    ('pervomaisky', 'school-70', 'bishkek', 'school', 'Школа №70', null),
    ('pervomaisky', 'school-75', 'bishkek', 'school', 'Школа №75', null),
    ('pervomaisky', 'school-78', 'bishkek', 'school', 'Школа №78', null),
    ('pervomaisky', 'school-81', 'bishkek', 'school', 'Школа №81', null),
    ('pervomaisky', 'school-83', 'bishkek', 'school', 'Школа №83', null),
    ('pervomaisky', 'school-86', 'bishkek', 'school', 'Школа №86', null),
    ('pervomaisky', 'school-gmeiner', 'bishkek', 'school', 'Школа им. Гмайнера', null),
    ('pervomaisky', 'school-internat-blind', 'bishkek', 'school', 'Специальная школа-интернат для слепых и слабовидящих детей', null),
    ('leninsky', 'bgu', 'bishkek', 'university', 'БГУ им. К. Карасаева', 'Бишкекский государственный университет'),
    ('leninsky', 'kgtu', 'bishkek', 'university', 'КГТУ им. И. Раззакова', 'Кыргызский государственный технический университет'),
    ('leninsky', 'manas', 'bishkek', 'university', 'КТУ «Манас»', 'Кыргызско-Турецкий университет'),
    ('leninsky', 'knau', 'bishkek', 'university', 'КНАУ им. К. И. Скрябина', 'Кыргызский национальный аграрный университет'),
    ('leninsky', 'muk', 'bishkek', 'university', 'МУК', 'Международный университет Кыргызстана'),
    ('leninsky', 'kgii', 'bishkek', 'university', 'КГИИ им. Б. Бейшеналиевой', 'Кыргызский государственный институт искусств'),
    ('leninsky', 'kgafkis', 'bishkek', 'university', 'КГАФКиС', 'Кыргызская государственная академия физической культуры и спорта'),
    ('leninsky', 'mvshm', 'bishkek', 'university', 'Международная Высшая Школа Медицины (МВШМ)', null),
    ('leninsky', 'school-2', 'bishkek', 'school', 'Школа №2', null),
    ('leninsky', 'school-7', 'bishkek', 'school', 'Школа №7', null),
    ('leninsky', 'school-8', 'bishkek', 'school', 'Школа №8', null),
    ('leninsky', 'school-9', 'bishkek', 'school', 'Школа №9', null),
    ('leninsky', 'school-10', 'bishkek', 'school', 'Школа №10', null),
    ('leninsky', 'school-13', 'bishkek', 'school', 'Школа №13', null),
    ('leninsky', 'school-22', 'bishkek', 'school', 'Школа №22', null),
    ('leninsky', 'school-25', 'bishkek', 'school', 'Школа №25', null),
    ('leninsky', 'school-31', 'bishkek', 'school', 'Школа №31', null),
    ('leninsky', 'school-40', 'bishkek', 'school', 'Школа №40', null),
    ('leninsky', 'school-42', 'bishkek', 'school', 'Школа №42', null),
    ('leninsky', 'school-44', 'bishkek', 'school', 'Школа №44', null),
    ('leninsky', 'school-47', 'bishkek', 'school', 'Школа №47', null),
    ('leninsky', 'school-50', 'bishkek', 'school', 'Школа №50', null),
    ('leninsky', 'school-55', 'bishkek', 'school', 'Школа №55', null),
    ('leninsky', 'school-57', 'bishkek', 'school', 'Школа №57', null),
    ('leninsky', 'school-58', 'bishkek', 'school', 'Школа №58', null),
    ('leninsky', 'school-59', 'bishkek', 'school', 'Школа №59', null),
    ('leninsky', 'school-68', 'bishkek', 'school', 'Школа №68', null),
    ('leninsky', 'school-72', 'bishkek', 'school', 'Школа №72', null),
    ('leninsky', 'school-74', 'bishkek', 'school', 'Школа №74', null),
    ('leninsky', 'school-77', 'bishkek', 'school', 'Школа №77', null),
    ('leninsky', 'school-79', 'bishkek', 'school', 'Школа №79', null),
    ('leninsky', 'school-80', 'bishkek', 'school', 'Школа №80', null),
    ('leninsky', 'school-82', 'bishkek', 'school', 'Школа №82', null),
    ('leninsky', 'school-84', 'bishkek', 'school', 'Школа №84', null),
    ('leninsky', 'school-90', 'bishkek', 'school', 'Школа №90', null),
    ('leninsky', 'school-93', 'bishkek', 'school', 'Школа №93', null),
    ('leninsky', 'school-95', 'bishkek', 'school', 'Школа №95', null),
    ('leninsky', 'school-96', 'bishkek', 'school', 'Школа №96', null),
    ('leninsky', 'school-art-internat', 'bishkek', 'school', 'Республиканская художественная школа-интернат', null),
    ('sverdlovsky', 'keu', 'bishkek', 'university', 'КЭУ им. М. Рыскулбекова', 'Кыргызский экономический университет'),
    ('sverdlovsky', 'osce-academy', 'bishkek', 'university', 'Академия ОБСЕ в Бишкеке', null),
    ('sverdlovsky', 'kica', 'bishkek', 'university', 'Корейский институт в Центральной Азии', null),
    ('sverdlovsky', 'muca', 'bishkek', 'university', 'МУЦА', 'Международный университет в Центральной Азии'),
    ('sverdlovsky', 'school-1', 'bishkek', 'school', 'Школа №1', null),
    ('sverdlovsky', 'school-4', 'bishkek', 'school', 'Школа №4', null),
    ('sverdlovsky', 'school-5', 'bishkek', 'school', 'Школа №5', null),
    ('sverdlovsky', 'school-10', 'bishkek', 'school', 'Школа №10', null),
    ('sverdlovsky', 'school-11', 'bishkek', 'school', 'Школа №11', null),
    ('sverdlovsky', 'school-12', 'bishkek', 'school', 'Школа №12', null),
    ('sverdlovsky', 'school-16', 'bishkek', 'school', 'Школа №16', null),
    ('sverdlovsky', 'school-21', 'bishkek', 'school', 'Школа №21', null),
    ('sverdlovsky', 'school-23', 'bishkek', 'school', 'Школа №23', null),
    ('sverdlovsky', 'school-30', 'bishkek', 'school', 'Школа №30', null),
    ('sverdlovsky', 'school-32', 'bishkek', 'school', 'Школа №32', null),
    ('sverdlovsky', 'school-33', 'bishkek', 'school', 'Школа №33', null),
    ('sverdlovsky', 'school-35', 'bishkek', 'school', 'Школа №35', null),
    ('sverdlovsky', 'school-38', 'bishkek', 'school', 'Школа №38', null),
    ('sverdlovsky', 'school-43', 'bishkek', 'school', 'Школа №43', null),
    ('sverdlovsky', 'school-45', 'bishkek', 'school', 'Школа №45', null),
    ('sverdlovsky', 'school-46', 'bishkek', 'school', 'Школа №46', null),
    ('sverdlovsky', 'school-51', 'bishkek', 'school', 'Школа №51', null),
    ('sverdlovsky', 'school-52', 'bishkek', 'school', 'Школа №52', null),
    ('sverdlovsky', 'school-53', 'bishkek', 'school', 'Школа №53', null),
    ('sverdlovsky', 'school-65', 'bishkek', 'school', 'Школа №65', null),
    ('sverdlovsky', 'school-66', 'bishkek', 'school', 'Школа №66', null),
    ('sverdlovsky', 'school-67', 'bishkek', 'school', 'Школа №67', null),
    ('sverdlovsky', 'school-76', 'bishkek', 'school', 'Школа №76', null),
    ('sverdlovsky', 'school-85', 'bishkek', 'school', 'Школа №85', null),
    ('sverdlovsky', 'school-87', 'bishkek', 'school', 'Школа №87', null),
    ('sverdlovsky', 'school-89', 'bishkek', 'school', 'Школа №89', null),
    ('sverdlovsky', 'school-94', 'bishkek', 'school', 'Школа №94', null),
    ('oktyabrsky', 'krsu', 'bishkek', 'university', 'КРСУ им. Б. Н. Ельцина', 'Кыргызско-Российский Славянский университет'),
    ('oktyabrsky', 'ala-too', 'bishkek', 'university', 'Международный университет «Ала-Тоо»', null),
    ('oktyabrsky', 'kgyua', 'bishkek', 'university', 'КГЮУ / КГЮА', 'Кыргызский государственный юридический университет / академия'),
    ('oktyabrsky', 'salymbekov', 'bishkek', 'university', 'Салымбеков Университет', null),
    ('oktyabrsky', 'maupfib', 'bishkek', 'university', 'МАУПФиБ', 'Международная академия управления, права, финансов и бизнеса'),
    ('oktyabrsky', 'school-3', 'bishkek', 'school', 'Школа №3', null),
    ('oktyabrsky', 'school-7', 'bishkek', 'school', 'Школа №7', null),
    ('oktyabrsky', 'school-14', 'bishkek', 'school', 'Школа №14', null),
    ('oktyabrsky', 'school-17', 'bishkek', 'school', 'Школа №17', null),
    ('oktyabrsky', 'school-20', 'bishkek', 'school', 'Школа №20', null),
    ('oktyabrsky', 'school-26', 'bishkek', 'school', 'Школа №26', null),
    ('oktyabrsky', 'school-34', 'bishkek', 'school', 'Школа №34', null),
    ('oktyabrsky', 'school-37', 'bishkek', 'school', 'Школа №37', null),
    ('oktyabrsky', 'school-39', 'bishkek', 'school', 'Школа №39', null),
    ('oktyabrsky', 'school-56', 'bishkek', 'school', 'Школа №56', null),
    ('oktyabrsky', 'school-60', 'bishkek', 'school', 'Школа №60', null),
    ('oktyabrsky', 'school-62', 'bishkek', 'school', 'Школа №62', null),
    ('oktyabrsky', 'school-63', 'bishkek', 'school', 'Школа №63', null),
    ('oktyabrsky', 'school-64', 'bishkek', 'school', 'Школа №64', null),
    ('oktyabrsky', 'school-71', 'bishkek', 'school', 'Школа №71', null),
    ('oktyabrsky', 'school-73', 'bishkek', 'school', 'Школа №73', null),
    ('oktyabrsky', 'school-88', 'bishkek', 'school', 'Школа №88', null),
    ('oktyabrsky', 'school-91', 'bishkek', 'school', 'Школа №91', null),
    ('oktyabrsky', 'school-92', 'bishkek', 'school', 'Школа №92', null)
  on conflict (district_id, id) do nothing;

  -- ── Сообщество города и его каналы ──
  insert into public.communities (id, city_id, name, category, description, emoji, is_private) values
    ('bishkek', 'bishkek', 'Бишкек', 'district', 'Общее пространство жителей Бишкека: каналы города, события и чаты по районам', '🏙️', false)
  on conflict (id) do nothing;

  insert into public.channels (community_id, name, description, emoji, is_announcements, is_pinned) values
    ('bishkek', 'general', 'Общий чат для всех', '💬', false, false),
    ('bishkek', 'announcements', 'Важные объявления', '📢', true, true),
    ('bishkek', 'lost-and-found', 'Потерянные и найденные вещи', '🔍', false, false),
    ('bishkek', 'events', 'Мероприятия сообщества', '🎉', false, false),
    ('bishkek', 'memes', 'Мемы и развлечения', '😂', false, false),
    ('bishkek', 'study', 'Учёба и помощь', '📚', false, false)
  on conflict (community_id, name) do nothing;

  -- ── Чаты по месту (145): общий, город, районы, учебные заведения ──
  -- Чтобы добавить чат — добавьте строку в таблицу chats (см. README), код менять не нужно.
  insert into public.chats (id, name, type, city_id, district_id, institution_id, description, emoji) values
    ('pervomaisky-knu-general', 'Общий чат — КНУ им. Ж. Баласагына', 'university', 'bishkek', 'pervomaisky', 'knu', 'Кыргызский национальный университет', null),
    ('pervomaisky-kgma-general', 'Общий чат — КГМА им. И. К. Ахунбаева', 'university', 'bishkek', 'pervomaisky', 'kgma', 'Кыргызская государственная медицинская академия', null),
    ('pervomaisky-kgu-general', 'Общий чат — КГУ им. И. Арабаева', 'university', 'bishkek', 'pervomaisky', 'kgu', 'Кыргызский государственный университет', null),
    ('pervomaisky-auca-general', 'Общий чат — АУЦА', 'university', 'bishkek', 'pervomaisky', 'auca', 'Американский университет в Центральной Азии', null),
    ('pervomaisky-knk-general', 'Общий чат — КНК им. К. Молдобасанова', 'university', 'bishkek', 'pervomaisky', 'knk', 'Кыргызская национальная консерватория', null),
    ('pervomaisky-school-1-general', 'Общий чат — Школа №1', 'school', 'bishkek', 'pervomaisky', 'school-1', null, null),
    ('pervomaisky-school-6-general', 'Общий чат — Школа №6', 'school', 'bishkek', 'pervomaisky', 'school-6', null, null),
    ('pervomaisky-school-15-general', 'Общий чат — Школа №15', 'school', 'bishkek', 'pervomaisky', 'school-15', null, null),
    ('pervomaisky-school-18-general', 'Общий чат — Школа №18', 'school', 'bishkek', 'pervomaisky', 'school-18', null, null),
    ('pervomaisky-school-19-general', 'Общий чат — Школа №19', 'school', 'bishkek', 'pervomaisky', 'school-19', null, null),
    ('pervomaisky-school-24-general', 'Общий чат — Школа №24', 'school', 'bishkek', 'pervomaisky', 'school-24', null, null),
    ('pervomaisky-school-27-general', 'Общий чат — Школа №27', 'school', 'bishkek', 'pervomaisky', 'school-27', null, null),
    ('pervomaisky-school-28-general', 'Общий чат — Школа №28', 'school', 'bishkek', 'pervomaisky', 'school-28', null, null),
    ('pervomaisky-school-29-general', 'Общий чат — Школа №29', 'school', 'bishkek', 'pervomaisky', 'school-29', null, null),
    ('pervomaisky-school-41-general', 'Общий чат — Школа №41', 'school', 'bishkek', 'pervomaisky', 'school-41', null, null),
    ('pervomaisky-school-48-general', 'Общий чат — Школа №48', 'school', 'bishkek', 'pervomaisky', 'school-48', null, null),
    ('pervomaisky-school-49-general', 'Общий чат — Школа №49', 'school', 'bishkek', 'pervomaisky', 'school-49', null, null),
    ('pervomaisky-school-54-general', 'Общий чат — Школа №54', 'school', 'bishkek', 'pervomaisky', 'school-54', null, null),
    ('pervomaisky-school-61-general', 'Общий чат — Школа №61', 'school', 'bishkek', 'pervomaisky', 'school-61', null, null),
    ('pervomaisky-school-69-general', 'Общий чат — Школа №69', 'school', 'bishkek', 'pervomaisky', 'school-69', null, null),
    ('pervomaisky-school-70-general', 'Общий чат — Школа №70', 'school', 'bishkek', 'pervomaisky', 'school-70', null, null),
    ('pervomaisky-school-75-general', 'Общий чат — Школа №75', 'school', 'bishkek', 'pervomaisky', 'school-75', null, null),
    ('pervomaisky-school-78-general', 'Общий чат — Школа №78', 'school', 'bishkek', 'pervomaisky', 'school-78', null, null),
    ('pervomaisky-school-81-general', 'Общий чат — Школа №81', 'school', 'bishkek', 'pervomaisky', 'school-81', null, null),
    ('pervomaisky-school-83-general', 'Общий чат — Школа №83', 'school', 'bishkek', 'pervomaisky', 'school-83', null, null),
    ('pervomaisky-school-86-general', 'Общий чат — Школа №86', 'school', 'bishkek', 'pervomaisky', 'school-86', null, null),
    ('pervomaisky-school-gmeiner-general', 'Общий чат — Школа им. Гмайнера', 'school', 'bishkek', 'pervomaisky', 'school-gmeiner', null, null),
    ('pervomaisky-school-internat-blind-general', 'Общий чат — Специальная школа-интернат для слепых и слабовидящих детей', 'school', 'bishkek', 'pervomaisky', 'school-internat-blind', null, null),
    ('leninsky-bgu-general', 'Общий чат — БГУ им. К. Карасаева', 'university', 'bishkek', 'leninsky', 'bgu', 'Бишкекский государственный университет', null),
    ('leninsky-kgtu-general', 'Общий чат — КГТУ им. И. Раззакова', 'university', 'bishkek', 'leninsky', 'kgtu', 'Кыргызский государственный технический университет', null),
    ('leninsky-manas-general', 'Общий чат — КТУ «Манас»', 'university', 'bishkek', 'leninsky', 'manas', 'Кыргызско-Турецкий университет', null),
    ('leninsky-knau-general', 'Общий чат — КНАУ им. К. И. Скрябина', 'university', 'bishkek', 'leninsky', 'knau', 'Кыргызский национальный аграрный университет', null),
    ('leninsky-muk-general', 'Общий чат — МУК', 'university', 'bishkek', 'leninsky', 'muk', 'Международный университет Кыргызстана', null),
    ('leninsky-kgii-general', 'Общий чат — КГИИ им. Б. Бейшеналиевой', 'university', 'bishkek', 'leninsky', 'kgii', 'Кыргызский государственный институт искусств', null),
    ('leninsky-kgafkis-general', 'Общий чат — КГАФКиС', 'university', 'bishkek', 'leninsky', 'kgafkis', 'Кыргызская государственная академия физической культуры и спорта', null),
    ('leninsky-mvshm-general', 'Общий чат — Международная Высшая Школа Медицины (МВШМ)', 'university', 'bishkek', 'leninsky', 'mvshm', null, null),
    ('leninsky-school-2-general', 'Общий чат — Школа №2', 'school', 'bishkek', 'leninsky', 'school-2', null, null),
    ('leninsky-school-7-general', 'Общий чат — Школа №7', 'school', 'bishkek', 'leninsky', 'school-7', null, null),
    ('leninsky-school-8-general', 'Общий чат — Школа №8', 'school', 'bishkek', 'leninsky', 'school-8', null, null),
    ('leninsky-school-9-general', 'Общий чат — Школа №9', 'school', 'bishkek', 'leninsky', 'school-9', null, null),
    ('leninsky-school-10-general', 'Общий чат — Школа №10', 'school', 'bishkek', 'leninsky', 'school-10', null, null),
    ('leninsky-school-13-general', 'Общий чат — Школа №13', 'school', 'bishkek', 'leninsky', 'school-13', null, null),
    ('leninsky-school-22-general', 'Общий чат — Школа №22', 'school', 'bishkek', 'leninsky', 'school-22', null, null),
    ('leninsky-school-25-general', 'Общий чат — Школа №25', 'school', 'bishkek', 'leninsky', 'school-25', null, null),
    ('leninsky-school-31-general', 'Общий чат — Школа №31', 'school', 'bishkek', 'leninsky', 'school-31', null, null),
    ('leninsky-school-40-general', 'Общий чат — Школа №40', 'school', 'bishkek', 'leninsky', 'school-40', null, null),
    ('leninsky-school-42-general', 'Общий чат — Школа №42', 'school', 'bishkek', 'leninsky', 'school-42', null, null),
    ('leninsky-school-44-general', 'Общий чат — Школа №44', 'school', 'bishkek', 'leninsky', 'school-44', null, null),
    ('leninsky-school-47-general', 'Общий чат — Школа №47', 'school', 'bishkek', 'leninsky', 'school-47', null, null),
    ('leninsky-school-50-general', 'Общий чат — Школа №50', 'school', 'bishkek', 'leninsky', 'school-50', null, null),
    ('leninsky-school-55-general', 'Общий чат — Школа №55', 'school', 'bishkek', 'leninsky', 'school-55', null, null),
    ('leninsky-school-57-general', 'Общий чат — Школа №57', 'school', 'bishkek', 'leninsky', 'school-57', null, null),
    ('leninsky-school-58-general', 'Общий чат — Школа №58', 'school', 'bishkek', 'leninsky', 'school-58', null, null),
    ('leninsky-school-59-general', 'Общий чат — Школа №59', 'school', 'bishkek', 'leninsky', 'school-59', null, null),
    ('leninsky-school-68-general', 'Общий чат — Школа №68', 'school', 'bishkek', 'leninsky', 'school-68', null, null),
    ('leninsky-school-72-general', 'Общий чат — Школа №72', 'school', 'bishkek', 'leninsky', 'school-72', null, null),
    ('leninsky-school-74-general', 'Общий чат — Школа №74', 'school', 'bishkek', 'leninsky', 'school-74', null, null),
    ('leninsky-school-77-general', 'Общий чат — Школа №77', 'school', 'bishkek', 'leninsky', 'school-77', null, null),
    ('leninsky-school-79-general', 'Общий чат — Школа №79', 'school', 'bishkek', 'leninsky', 'school-79', null, null),
    ('leninsky-school-80-general', 'Общий чат — Школа №80', 'school', 'bishkek', 'leninsky', 'school-80', null, null),
    ('leninsky-school-82-general', 'Общий чат — Школа №82', 'school', 'bishkek', 'leninsky', 'school-82', null, null),
    ('leninsky-school-84-general', 'Общий чат — Школа №84', 'school', 'bishkek', 'leninsky', 'school-84', null, null),
    ('leninsky-school-90-general', 'Общий чат — Школа №90', 'school', 'bishkek', 'leninsky', 'school-90', null, null),
    ('leninsky-school-93-general', 'Общий чат — Школа №93', 'school', 'bishkek', 'leninsky', 'school-93', null, null),
    ('leninsky-school-95-general', 'Общий чат — Школа №95', 'school', 'bishkek', 'leninsky', 'school-95', null, null),
    ('leninsky-school-96-general', 'Общий чат — Школа №96', 'school', 'bishkek', 'leninsky', 'school-96', null, null),
    ('leninsky-school-art-internat-general', 'Общий чат — Республиканская художественная школа-интернат', 'school', 'bishkek', 'leninsky', 'school-art-internat', null, null),
    ('sverdlovsky-keu-general', 'Общий чат — КЭУ им. М. Рыскулбекова', 'university', 'bishkek', 'sverdlovsky', 'keu', 'Кыргызский экономический университет', null),
    ('sverdlovsky-osce-academy-general', 'Общий чат — Академия ОБСЕ в Бишкеке', 'university', 'bishkek', 'sverdlovsky', 'osce-academy', null, null),
    ('sverdlovsky-kica-general', 'Общий чат — Корейский институт в Центральной Азии', 'university', 'bishkek', 'sverdlovsky', 'kica', null, null),
    ('sverdlovsky-muca-general', 'Общий чат — МУЦА', 'university', 'bishkek', 'sverdlovsky', 'muca', 'Международный университет в Центральной Азии', null),
    ('sverdlovsky-school-1-general', 'Общий чат — Школа №1', 'school', 'bishkek', 'sverdlovsky', 'school-1', null, null),
    ('sverdlovsky-school-4-general', 'Общий чат — Школа №4', 'school', 'bishkek', 'sverdlovsky', 'school-4', null, null),
    ('sverdlovsky-school-5-general', 'Общий чат — Школа №5', 'school', 'bishkek', 'sverdlovsky', 'school-5', null, null),
    ('sverdlovsky-school-10-general', 'Общий чат — Школа №10', 'school', 'bishkek', 'sverdlovsky', 'school-10', null, null),
    ('sverdlovsky-school-11-general', 'Общий чат — Школа №11', 'school', 'bishkek', 'sverdlovsky', 'school-11', null, null),
    ('sverdlovsky-school-12-general', 'Общий чат — Школа №12', 'school', 'bishkek', 'sverdlovsky', 'school-12', null, null),
    ('sverdlovsky-school-16-general', 'Общий чат — Школа №16', 'school', 'bishkek', 'sverdlovsky', 'school-16', null, null),
    ('sverdlovsky-school-21-general', 'Общий чат — Школа №21', 'school', 'bishkek', 'sverdlovsky', 'school-21', null, null),
    ('sverdlovsky-school-23-general', 'Общий чат — Школа №23', 'school', 'bishkek', 'sverdlovsky', 'school-23', null, null),
    ('sverdlovsky-school-30-general', 'Общий чат — Школа №30', 'school', 'bishkek', 'sverdlovsky', 'school-30', null, null),
    ('sverdlovsky-school-32-general', 'Общий чат — Школа №32', 'school', 'bishkek', 'sverdlovsky', 'school-32', null, null),
    ('sverdlovsky-school-33-general', 'Общий чат — Школа №33', 'school', 'bishkek', 'sverdlovsky', 'school-33', null, null),
    ('sverdlovsky-school-35-general', 'Общий чат — Школа №35', 'school', 'bishkek', 'sverdlovsky', 'school-35', null, null),
    ('sverdlovsky-school-38-general', 'Общий чат — Школа №38', 'school', 'bishkek', 'sverdlovsky', 'school-38', null, null),
    ('sverdlovsky-school-43-general', 'Общий чат — Школа №43', 'school', 'bishkek', 'sverdlovsky', 'school-43', null, null),
    ('sverdlovsky-school-45-general', 'Общий чат — Школа №45', 'school', 'bishkek', 'sverdlovsky', 'school-45', null, null),
    ('sverdlovsky-school-46-general', 'Общий чат — Школа №46', 'school', 'bishkek', 'sverdlovsky', 'school-46', null, null),
    ('sverdlovsky-school-51-general', 'Общий чат — Школа №51', 'school', 'bishkek', 'sverdlovsky', 'school-51', null, null),
    ('sverdlovsky-school-52-general', 'Общий чат — Школа №52', 'school', 'bishkek', 'sverdlovsky', 'school-52', null, null),
    ('sverdlovsky-school-53-general', 'Общий чат — Школа №53', 'school', 'bishkek', 'sverdlovsky', 'school-53', null, null),
    ('sverdlovsky-school-65-general', 'Общий чат — Школа №65', 'school', 'bishkek', 'sverdlovsky', 'school-65', null, null),
    ('sverdlovsky-school-66-general', 'Общий чат — Школа №66', 'school', 'bishkek', 'sverdlovsky', 'school-66', null, null),
    ('sverdlovsky-school-67-general', 'Общий чат — Школа №67', 'school', 'bishkek', 'sverdlovsky', 'school-67', null, null),
    ('sverdlovsky-school-76-general', 'Общий чат — Школа №76', 'school', 'bishkek', 'sverdlovsky', 'school-76', null, null),
    ('sverdlovsky-school-85-general', 'Общий чат — Школа №85', 'school', 'bishkek', 'sverdlovsky', 'school-85', null, null),
    ('sverdlovsky-school-87-general', 'Общий чат — Школа №87', 'school', 'bishkek', 'sverdlovsky', 'school-87', null, null),
    ('sverdlovsky-school-89-general', 'Общий чат — Школа №89', 'school', 'bishkek', 'sverdlovsky', 'school-89', null, null),
    ('sverdlovsky-school-94-general', 'Общий чат — Школа №94', 'school', 'bishkek', 'sverdlovsky', 'school-94', null, null),
    ('oktyabrsky-krsu-general', 'Общий чат — КРСУ им. Б. Н. Ельцина', 'university', 'bishkek', 'oktyabrsky', 'krsu', 'Кыргызско-Российский Славянский университет', null),
    ('oktyabrsky-ala-too-general', 'Общий чат — Международный университет «Ала-Тоо»', 'university', 'bishkek', 'oktyabrsky', 'ala-too', null, null),
    ('oktyabrsky-kgyua-general', 'Общий чат — КГЮУ / КГЮА', 'university', 'bishkek', 'oktyabrsky', 'kgyua', 'Кыргызский государственный юридический университет / академия', null),
    ('oktyabrsky-salymbekov-general', 'Общий чат — Салымбеков Университет', 'university', 'bishkek', 'oktyabrsky', 'salymbekov', null, null),
    ('oktyabrsky-maupfib-general', 'Общий чат — МАУПФиБ', 'university', 'bishkek', 'oktyabrsky', 'maupfib', 'Международная академия управления, права, финансов и бизнеса', null),
    ('oktyabrsky-school-3-general', 'Общий чат — Школа №3', 'school', 'bishkek', 'oktyabrsky', 'school-3', null, null),
    ('oktyabrsky-school-7-general', 'Общий чат — Школа №7', 'school', 'bishkek', 'oktyabrsky', 'school-7', null, null),
    ('oktyabrsky-school-14-general', 'Общий чат — Школа №14', 'school', 'bishkek', 'oktyabrsky', 'school-14', null, null),
    ('oktyabrsky-school-17-general', 'Общий чат — Школа №17', 'school', 'bishkek', 'oktyabrsky', 'school-17', null, null),
    ('oktyabrsky-school-20-general', 'Общий чат — Школа №20', 'school', 'bishkek', 'oktyabrsky', 'school-20', null, null),
    ('oktyabrsky-school-26-general', 'Общий чат — Школа №26', 'school', 'bishkek', 'oktyabrsky', 'school-26', null, null),
    ('oktyabrsky-school-34-general', 'Общий чат — Школа №34', 'school', 'bishkek', 'oktyabrsky', 'school-34', null, null),
    ('oktyabrsky-school-37-general', 'Общий чат — Школа №37', 'school', 'bishkek', 'oktyabrsky', 'school-37', null, null),
    ('oktyabrsky-school-39-general', 'Общий чат — Школа №39', 'school', 'bishkek', 'oktyabrsky', 'school-39', null, null),
    ('oktyabrsky-school-56-general', 'Общий чат — Школа №56', 'school', 'bishkek', 'oktyabrsky', 'school-56', null, null),
    ('oktyabrsky-school-60-general', 'Общий чат — Школа №60', 'school', 'bishkek', 'oktyabrsky', 'school-60', null, null),
    ('oktyabrsky-school-62-general', 'Общий чат — Школа №62', 'school', 'bishkek', 'oktyabrsky', 'school-62', null, null),
    ('oktyabrsky-school-63-general', 'Общий чат — Школа №63', 'school', 'bishkek', 'oktyabrsky', 'school-63', null, null),
    ('oktyabrsky-school-64-general', 'Общий чат — Школа №64', 'school', 'bishkek', 'oktyabrsky', 'school-64', null, null),
    ('oktyabrsky-school-71-general', 'Общий чат — Школа №71', 'school', 'bishkek', 'oktyabrsky', 'school-71', null, null),
    ('oktyabrsky-school-73-general', 'Общий чат — Школа №73', 'school', 'bishkek', 'oktyabrsky', 'school-73', null, null),
    ('oktyabrsky-school-88-general', 'Общий чат — Школа №88', 'school', 'bishkek', 'oktyabrsky', 'school-88', null, null),
    ('oktyabrsky-school-91-general', 'Общий чат — Школа №91', 'school', 'bishkek', 'oktyabrsky', 'school-91', null, null),
    ('oktyabrsky-school-92-general', 'Общий чат — Школа №92', 'school', 'bishkek', 'oktyabrsky', 'school-92', null, null),
    ('global-community', 'Global Community', 'general', null, null, null, 'Общий чат всех пользователей приложения', null),
    ('bishkek-city', 'Бишкек', 'city', 'bishkek', null, null, 'Общий чат жителей Бишкека', null),
    ('pervomaisky-general', 'Общий чат Первомайского района', 'district', 'bishkek', 'pervomaisky', null, null, null),
    ('pervomaisky-news', 'Новости Первомайского', 'district', 'bishkek', 'pervomaisky', null, null, '📢'),
    ('pervomaisky-events', 'Мероприятия Первомайского', 'district', 'bishkek', 'pervomaisky', null, null, '🎉'),
    ('pervomaisky-lost-found', 'Потеряшки Первомайского', 'district', 'bishkek', 'pervomaisky', null, null, '🔍'),
    ('pervomaisky-youth', 'Молодёжь Первомайского', 'district', 'bishkek', 'pervomaisky', null, null, '🧑‍🤝‍🧑'),
    ('pervomaisky-sport', 'Спорт в Первомайском', 'district', 'bishkek', 'pervomaisky', null, null, '⚽'),
    ('leninsky-general', 'Общий чат Ленинского района', 'district', 'bishkek', 'leninsky', null, null, null),
    ('leninsky-dzhal', 'Джал', 'district', 'bishkek', 'leninsky', null, null, '🏘️'),
    ('leninsky-politeh', 'Политех', 'district', 'bishkek', 'leninsky', null, null, '🏘️'),
    ('leninsky-events', 'Мероприятия Ленинского района', 'district', 'bishkek', 'leninsky', null, null, '🎉'),
    ('sverdlovsky-general', 'Общий чат Свердловского района', 'district', 'bishkek', 'sverdlovsky', null, null, null),
    ('oktyabrsky-general', 'Общий чат Октябрьского района', 'district', 'bishkek', 'oktyabrsky', null, null, null),
    ('knu-students', 'Студенты КНУ', 'university', 'bishkek', 'pervomaisky', 'knu', null, '🧑‍🎓'),
    ('knu-news', 'Новости КНУ', 'university', 'bishkek', 'pervomaisky', 'knu', null, '📢'),
    ('knu-events', 'Мероприятия КНУ', 'university', 'bishkek', 'pervomaisky', 'knu', null, '🎉'),
    ('knu-lost-found', 'Потеряшки КНУ', 'university', 'bishkek', 'pervomaisky', 'knu', null, '🔍'),
    ('kgtu-students', 'Студенты КГТУ', 'university', 'bishkek', 'leninsky', 'kgtu', null, '🧑‍🎓'),
    ('pervomaisky-school-61-students', 'Ученики школы №61', 'school', 'bishkek', 'pervomaisky', 'school-61', null, '🎒'),
    ('pervomaisky-school-61-events', 'Мероприятия школы №61', 'school', 'bishkek', 'pervomaisky', 'school-61', null, '🎉'),
    ('pervomaisky-school-61-lost-found', 'Потеряшки школы №61', 'school', 'bishkek', 'pervomaisky', 'school-61', null, '🔍')
  -- Автоматически созданный чат (триггер справочника) получает название и описание из начальных данных
  on conflict (id) do update set name = excluded.name, description = excluded.description, emoji = excluded.emoji;

  -- ── Локальные чаты раздела «Рядом» ──
  insert into public.chats (id, name, type, community_id, description, emoji) values
    ('house-50', 'Дом №50', 'local', 'bishkek', 'Жители дома №50', '🏠'),
    ('entrance-2', 'Подъезд №2', 'local', 'bishkek', 'Подъезд №2, дом №50', '🚪'),
    ('yard', 'Двор', 'local', 'bishkek', 'Общий двор сообщества', '🌳'),
    ('library', 'Библиотека', 'local', 'bishkek', 'Районная библиотека', '📚'),
    ('sports-ground', 'Спортивная площадка', 'local', 'bishkek', 'Площадка возле корп. 2', '⚽'),
    ('canteen', 'Столовая', 'local', 'bishkek', 'Столовая рядом с домом', '🍽️')
  on conflict (id) do nothing;

  -- ── Мероприятия (организатор не указан — это демо-данные) ──
  insert into public.events (id, community_id, title, description, emoji, starts_at, location, max_attendees) values
    (md5('seed-event-1')::uuid, 'bishkek', 'Футбольный матч во дворе', 'Дружеский матч между классами. Приходите поддержать свою команду!', '⚽', now() + interval '6084 minutes', 'Спортивная площадка, корп. 2', 22),
    (md5('seed-event-2')::uuid, 'bishkek', 'Встреча в библиотеке', 'Совместная подготовка к контрольной и обмен конспектами по математике', '📚', now() + interval '7464 minutes', 'Библиотека, 2-й этаж', 15),
    (md5('seed-event-3')::uuid, 'bishkek', 'Осенний концерт', 'Концерт самодеятельности. Выступают ученики 5–11 классов. Приглашаем всех!', '🎭', now() + interval '14844 minutes', 'Актовый зал', null),
    (md5('seed-event-4')::uuid, 'bishkek', 'Подготовка к экзаменам', 'Помогаем друг другу разобраться с трудными темами по физике и химии', '✏️', now() + interval '10284 minutes', 'Кабинет 305', 20)
  on conflict (id) do nothing;

  -- ── Тестовые сообщения (без авторов: автор в чатах всегда «Анонимно») ──
  insert into public.messages (id, chat_id, channel_id, type, content, reply_to_id, created_at) values
    (md5('seed-message-g1')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Доброе утро, Бишкек! Желаю всем продуктивного дня 🌅', null, now() - interval '156 minutes'),
    (md5('seed-message-g-sys1')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'system', '✨ В сообщество вступил новый участник', null, now() - interval '111 minutes'),
    (md5('seed-message-g2')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Всем привет! Рад быть здесь 🙂', null, now() - interval '110 minutes'),
    (md5('seed-message-g3')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Привет! Добро пожаловать 👋', null, now() - interval '108 minutes'),
    (md5('seed-message-g4')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Эй, кто придёт на тренировку сегодня в 16:00? Нам нужен ещё один игрок ⚽', null, now() - interval '84 minutes'),
    (md5('seed-message-g5')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Я не играю в футбол, но могу поболеть 😄', md5('seed-message-g4')::uuid, now() - interval '81 minutes'),
    (md5('seed-message-g6')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Я приду! И сфотографирую для школьной газеты 📸', null, now() - interval '79 minutes'),
    (md5('seed-message-g7')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Кто сегодня идёт в библиотеку после уроков?', null, now() - interval '54 minutes'),
    (md5('seed-message-g8')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Я буду после 15:00 📚', null, now() - interval '51 minutes'),
    (md5('seed-message-g9')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Отлично, давайте встретимся там! У меня доклад по истории нужно доделать', null, now() - interval '49 minutes'),
    (md5('seed-message-g10')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Тоже приду! У меня доклад по биологии на завтра 😅', null, now() - interval '44 minutes'),
    (md5('seed-message-g11')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', 'Ребята, напоминаю — завтра контрольная по математике в 9–11 классах. Не забудьте взять калькуляторы!', null, now() - interval '21 minutes'),
    (md5('seed-message-g12')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'general'), 'text', '😱 Спасибо что напомнили, совсем забыл!', null, now() - interval '19 minutes'),
    (md5('seed-message-a1')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'announcements'), 'text', '📢 Уважаемые жители!

  В субботу в 15:00 в сквере пройдёт городской субботник. Инвентарь выдадут на месте — приходите всей семьёй!', null, now() - interval '18636 minutes'),
    (md5('seed-message-a2')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'announcements'), 'text', '📋 Расписание на следующую неделю изменено. Пожалуйста, проверьте актуальное расписание на сайте школы или в приложении.', null, now() - interval '6786 minutes'),
    (md5('seed-message-a3')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'announcements'), 'text', '🏆 Поздравляем команду Бишкека — 2-е место на республиканской олимпиаде по математике! Молодцы, ребята!', null, now() - interval '4111 minutes'),
    (md5('seed-message-lf1')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'lost-and-found'), 'text', '🎒 Кто-нибудь видел синий рюкзак с нашивкой «NASA»? Потерял вчера, возможно в классе 312 или столовой', null, now() - interval '161 minutes'),
    (md5('seed-message-lf2')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'lost-and-found'), 'text', 'Нашла синий рюкзак возле спортзала! Сдала на вахту 🎒', null, now() - interval '126 minutes'),
    (md5('seed-message-lf3')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'lost-and-found'), 'text', 'Огромное спасибо! Сейчас иду забирать 🙏', null, now() - interval '123 minutes'),
    (md5('seed-message-s1')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'study'), 'text', 'Кто решил задачу 5 из параграфа 12 по физике? Никак не могу понять про электрическое поле 😤', null, now() - interval '101 minutes'),
    (md5('seed-message-s2')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'study'), 'text', 'Я решил! Там надо использовать закон Кулона. Скинуть решение?', null, now() - interval '94 minutes'),
    (md5('seed-message-s3')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'study'), 'text', 'Да пожалуйста! Буду очень признательна', null, now() - interval '93 minutes'),
    (md5('seed-message-s4')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'study'), 'text', 'Я тоже не могла разобраться, было бы здорово увидеть решение 🙏', null, now() - interval '86 minutes'),
    (md5('seed-message-m1')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'memes'), 'text', 'Когда учитель говорит "это не войдёт в контрольную", а потом добавляет первым вопросом 😂', null, now() - interval '126 minutes'),
    (md5('seed-message-m2')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'memes'), 'text', 'Я: ладно, последний ролик на ютубе и спать
  Я в 3 ночи:', null, now() - interval '101 minutes'),
    (md5('seed-message-ev1')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'events'), 'text', '⚽ Всем привет! Организую футбольный матч в пятницу в 16:00 на спортивной площадке. Нужны игроки!', null, now() - interval '976 minutes'),
    (md5('seed-message-ev2')::uuid, null, (select id from public.channels where community_id = 'bishkek' and name = 'events'), 'text', 'Я приду смотреть! Будет замечательно', null, now() - interval '962 minutes'),
    (md5('seed-message-l-h1')::uuid, 'house-50', null, 'text', 'Кто-нибудь знает, когда отключат воду?', null, now() - interval '12 minutes'),
    (md5('seed-message-l-h2')::uuid, 'house-50', null, 'text', 'Хороший вопрос! Я тоже хотел узнать', null, now() - interval '5 minutes'),
    (md5('seed-message-l-h3')::uuid, 'house-50', null, 'text', 'Напишу в чат управляющей компании', null, now() - interval '2 minutes'),
    (md5('seed-message-l-e1')::uuid, 'entrance-2', null, 'text', 'Новый код домофона — 4521', null, now() - interval '15 minutes'),
    (md5('seed-message-l-y1')::uuid, 'yard', null, 'text', '🍽 Кто сегодня готовит ужин во дворе? Присоединяйтесь!', null, now() - interval '34 minutes'),
    (md5('seed-message-l-l1')::uuid, 'library', null, 'text', '📚 Кто сегодня остаётся после 20:00?', null, now() - interval '60 minutes'),
    (md5('seed-message-l-s1')::uuid, 'sports-ground', null, 'text', '⚽ Кто играет сегодня вечером?', null, now() - interval '45 minutes'),
    (md5('seed-message-l-c1')::uuid, 'canteen', null, 'text', 'Сегодня на обед борщ и котлеты 🍲', null, now() - interval '120 minutes'),
    (md5('seed-message-p-c1')::uuid, 'bishkek-city', null, 'text', 'Кто знает, будет ли в субботу ярмарка на площади?', null, now() - interval '91 minutes'),
    (md5('seed-message-p-c2')::uuid, 'bishkek-city', null, 'text', 'Да, с 10:00 до 18:00 🎪', null, now() - interval '85 minutes'),
    (md5('seed-message-p-d1')::uuid, 'pervomaisky-general', null, 'text', 'Во дворе у дома 12 сегодня отключат свет с 14 до 16', null, now() - interval '136 minutes'),
    (md5('seed-message-p-d2')::uuid, 'pervomaisky-general', null, 'text', 'Спасибо, что предупредили!', md5('seed-message-p-d1')::uuid, now() - interval '129 minutes'),
    (md5('seed-message-p-s1')::uuid, 'pervomaisky-school-61-general', null, 'text', 'Кто-нибудь знает, во сколько завтра классный час?', null, now() - interval '166 minutes'),
    (md5('seed-message-p-s2')::uuid, 'pervomaisky-school-61-general', null, 'text', 'В 13:00 в актовом зале', null, now() - interval '158 minutes'),
    (md5('seed-message-p-g1')::uuid, 'global-community', null, 'text', 'Привет всем из Global Community! 👋', null, now() - interval '34 minutes'),
    (md5('seed-message-p-k1')::uuid, 'knu-news', null, 'text', '📢 Расписание зимней сессии опубликовано на сайте университета', null, now() - interval '1076 minutes')
  on conflict (id) do nothing;
